parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: msm
    database_user: root
    database_password: teamo0707
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 134359f5d0fc245ef69586791bfb2109
    database_driver: pdo_mysql
    database_path: null
