<?php

namespace MSM\ProductosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LubricantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LubricantesRepository extends EntityRepository
{
}
